// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrlKAys4_d3DnYSB3rnC3UQSLvDjg2Zww',
    appId: '1:925678225145:web:4d2bcad1a2eebaabe8c428',
    messagingSenderId: '925678225145',
    projectId: 'idphoto-e5a75',
    authDomain: 'idphoto-e5a75.firebaseapp.com',
    databaseURL: 'https://idphoto-e5a75-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'idphoto-e5a75.firebasestorage.app',
    measurementId: 'G-2DDPYB3G7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSac8qdkg8CBFrYMQM9i46V5b4mcEIw7I',
    appId: '1:925678225145:android:e84df6fe975672c3e8c428',
    messagingSenderId: '925678225145',
    projectId: 'idphoto-e5a75',
    databaseURL: 'https://idphoto-e5a75-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'idphoto-e5a75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1pC7hNmNUap9e2U-Rm5KBQD67bOEuH1o',
    appId: '1:925678225145:ios:09f23cdd39d45076e8c428',
    messagingSenderId: '925678225145',
    projectId: 'idphoto-e5a75',
    databaseURL: 'https://idphoto-e5a75-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'idphoto-e5a75.firebasestorage.app',
    iosBundleId: 'com.example.easycropE1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1pC7hNmNUap9e2U-Rm5KBQD67bOEuH1o',
    appId: '1:925678225145:ios:09f23cdd39d45076e8c428',
    messagingSenderId: '925678225145',
    projectId: 'idphoto-e5a75',
    databaseURL: 'https://idphoto-e5a75-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'idphoto-e5a75.firebasestorage.app',
    iosBundleId: 'com.example.easycropE1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrlKAys4_d3DnYSB3rnC3UQSLvDjg2Zww',
    appId: '1:925678225145:web:b62b2b6e3d97437de8c428',
    messagingSenderId: '925678225145',
    projectId: 'idphoto-e5a75',
    authDomain: 'idphoto-e5a75.firebaseapp.com',
    databaseURL: 'https://idphoto-e5a75-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'idphoto-e5a75.firebasestorage.app',
    measurementId: 'G-VRGCHCBH2M',
  );
}
